PORT = "/dev/ttyACM0"
BAUD = 1000000

SERVO_CONFIG = "servos.json"
POSE_DIR = "poses"
GESTURE_DIR = "gestures"
BEHAVIOUR_DIR = "behaviours"

ADDR_TORQUE_ENABLE = 40
ADDR_GOAL_POSITION = 42
ADDR_MOVING_SPEED = 46
ADDR_PRESENT_POSITION = 56
ADDR_PRESENT_SPEED = 58
ADDR_PRESENT_LOAD = 60
ADDR_PRESENT_VOLTAGE = 62
ADDR_PRESENT_TEMPERATURE = 63
ADDR_MOVING = 66

DEFAULT_SPEED = 500
DEFAULT_DELAY_MS = 500
RECORD_INTERVAL = 0.1
